config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    resources :posts, only: [:create, :index]
  end
  resources :posts, only: [:show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :index]
  end
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord

    has_many :posts
    has_and_belongs_to_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :comments
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      redirect_to post_path(@post), alert: 'Failed to create comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts.page(params[:page])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@like = @post.likes.build(user: current_user)
		if @like.save
			redirect_to post_path(@post), notice: 'Post liked.'
		else
			redirect_to post_path(@post), alert: 'Unable to like post.'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@like = @post.likes.find_by(user: current_user)
		@like.destroy if @like
		redirect_to post_path(@post), notice: 'Post unliked.'
	end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_id])
    @post = @group.posts.build(post_params)
    @post.user = current_user
    if @post.save
      redirect_to group_path(@group), notice: 'Post was successfully created.'
    else
      redirect_to group_path(@group), alert: 'Failed to create post.'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/index.html.erb
<h1>Groups</h1>
<div class="row">
  <% @groups.each do |group| %>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title"><%= link_to group.name, group %></h5>
          <p class="card-text"><%= group.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<!-- app/views/groups/show.html.erb -->
<h1><%= @group.name %></h1>
<p><%= @group.description %></p>

<h2>Posts</h2>
<%= form_with model: [@group, Post.new], local: true do |form| %>
  <div>
    <%= form.text_area :content %>
    <%= form.submit 'Post' %>
  </div>
<% end %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.content, post_path(post) %>
      - <%= post.user.email %>
    </li>
  <% end %>
</ul>

<%= paginate @posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNetwork</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">SocialNetwork</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/groups">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_in">Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign Up</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/show.html.erb
<h1>Post by <%= @post.user.email %></h1>
<p><%= @post.content %></p>

<h2>Likes</h2>
<% if @post.likes.find_by(user: current_user) %>
  <%= form_with(url: post_like_path(@post, @post.likes.find_by(user: current_user)), method: :delete, data: { turbo_frame: 'form-target', turbo_method: :delete, confirm: 'Are you sure?' }) do %>
    <%= submit_tag 'Unlike' %>
  <% end %>
<% else %>
  <%= form_with(url: post_likes_path(@post), method: :post, data: { turbo_frame: 'form-target' }) do %>
    <%= submit_tag 'Like', data: { turbo_method: :post } %>
  <% end %>
<% end %>
<span><%= pluralize(@post.likes.count, 'like') %></span>



<h2>Comments</h2>
<%= form_with model: [@post, Comment.new], local: true do |form| %>
  <div>
    <%= form.text_area :content %>
    <%= form.submit 'Comment' %>
  </div>
<% end %>

<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= comment.content %>
      - <%= comment.user.email %>
    </li>
  <% end %>
</ul>

<%= paginate @comments %>